DATABASE & ROUTING:
Are DB Connections Correct? 
Is routing properly configured ?
How to seed & test?
Generate Seed or Create one within the route?


POSTMAN: 
- When to set XSRF-Token for production 


ROUTES:
1 - (Get Current User) How to reorder ?
1 - (Log-in) How to handle credential ? is this already defined in the provided route? Does Order matter
2 - (Sign Up) Do We need to return data in the order given? -> If so can we organize the data at the route level?

